git:
  depth: 3  
cache:
  directories:
  - ~/.composer/cache/
  - ~/.npm
  - ~/.codacy-coverage

jobs:
  include:
  - language: node_js
    node_js: node
    stage: Test
    name: liniting
    install:
    - npm install
    script:
    - npm run-script lint
  - language: node_js
    node_js: node
    stage: Test
    name: unittest
    install:
    - npm install
    script:
    - npm test
    after_success:
    - bash <(wget -q -O - https://coverage.codacy.com/get.sh) report -r coverage/lcov.info
