git:
  depth: 3  
cache:
  directories:
  - ~/.composer/cache/
  - ~/.npm

jobs:
  include:
  - language: node_js
    node_js: node
    stage: Test
    name: liniting
    install:
    - npm install
    script:
    - npm run-script lint
  - language: node_js
    node_js: node
    stage: Test
    name: unittest
    install:
    - npm install
    script:
    - npm test
