name: cli FTA
on:
  push:
    branches:
    - master
    paths:
    - 'cli/**.ts'
    - 'cli/**.tsx'
    - 'cli/**.js'
    - 'cli/**.cjs'
    - 'cli/**.json'
    - 'cli/**.svelte'
    - '.github/workflows/cli.fta.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'cli/**.ts'
    - 'cli/**.tsx'
    - 'cli/**.js'
    - 'cli/**.cjs'
    - 'cli/**.json'
    - 'cli/**.svelte'
    - '.github/workflows/cli.fta.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - run: cd cli && npm ci && npm run language
      - run: npm run fta -- cli || true
