name: cli license lint
on:
  push:
    branches:
      - the-one
    paths:
      - 'cli/package-lock.json'
      - '.github/workflows/cli.license-check.yml'
  pull_request:
    branches:
      - the-one
    paths:
      - 'cli/package-lock.json'
      - '.github/workflows/cli.license-check.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            documentation-website/package-lock.json
            history-microservice/package-lock.json
            history-website/package-lock.json
            cli/package-lock.json
            package-lock.json
      - run: cd cli && npm ci
      - run: cd cli && npx license-checker -- --production --onlyAllow="MIT;ISC;Apache-2.0;BSD-2-Clause;BSD-3-Clause;Python-2.0;LGPL-2.1;GPL-2.0;BlueOak-1.0.0;CC0-1.0;0BSD;WTFPL;Unlicense"
