name: MARKDOWN-LINT
on:
  push:
    branches:
    - master
    paths:
    - 'cli/**.md'
    - 'cli/package-lock.json'
    - '.github/workflows/cli.mdlint.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'cli/**.md'
    - 'cli/package-lock.json'
    - '.github/workflows/cli.mdlint.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: cd cli && npm ci
      - run: cd cli && npm run lint-md
