name: Docker
on:
  push:
    branches:
      - master
    paths:
      - 'containers/*/Dockerfile'
      - '.github/workflows/docker.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'containers/*/Dockerfile'
      - '.github/workflows/docker.yml'
jobs:
  builder:
    name: Builder
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: git fetch --tags
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('containers/api-bench-build/Dockerfile') }}
      - run: docker build --build-arg="BUILD_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" -t "idrinth/api-bench-build:$(git describe --tags `git rev-list --tags --max-count=1`)" --build-arg="BUILD_TIME=now" containers/api-bench-build
  build:
    needs:
      - builder
    strategy:
      matrix:
        folder:
          - 'api-bench-gitlab-runner'
          - 'api-bench'
          - 'api-bench-gitea-action'
          - 'api-bench-history-website'
          - 'api-bench-history-microservice'
    name: Build ${{ matrix.folder }}
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: git fetch --all
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('containers/api-bench-build/Dockerfile') }}
          read-only: true
      - run: docker build --build-arg="BUILD_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)" --build-arg="BUILD_TIME=now" containers/${{ matrix.folder }}
