name: documentation-website Knip
on:
  workflow_run:
    types:
      - completed
    workflows:
      - NPM Cache
    paths:
    - 'documentation-website/**.ts'
    - 'documentation-website/**.tsx'
    - 'documentation-website/**.js'
    - 'documentation-website/**.cjs'
    - 'documentation-website/**.json'
    - 'documentation-website/**.svelte'
    - '.github/workflows/documentation-website.knip.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: npm ci
      - run: cd documentation-website && npm ci
      - run: cd documentation-website && npm run language
      - run: cd documentation-website && npm run knip
