name: Documentation Website STYLELINT
on:
  push:
    branches:
    - master
    paths:
    - 'documentation-website/**.scss'
    - 'documentation-website/package-lock.json'
    - '.github/workflows/documentation-website.stylelint.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'documentation-website/**.scss'
    - 'documentation-website/package-lock.json'
    - '.github/workflows/documentation-website.stylelint.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: cd documentation-website && npm ci
      - run: cd documentation-website && npm run lint-styles
  duplicate-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: cd documentation-website && npm ci
      - run: cd documentation-website && npm run lint-css
