name: documentation-website lighthouse check
on:
  workflow_run:
    types:
      - completed
    workflows:
      - NPM Cache
    paths:
      - 'documentation-website/**.ts'
      - 'documentation-website/**.tsx'
      - 'documentation-website/**.js'
      - 'documentation-website/**.cjs'
      - 'documentation-website/package-lock.json'
      - '.github/workflows/documentation-website.lighthouse-check.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript-typescript
        queries: security-and-quality
        source-root: documentation-website
    - name: Setup Node.js environment ${{ env.CURRENT_NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.CURRENT_NODE_VERSION }}
    - name: Wait for cache to be built
      uses: lewagon/wait-on-check-action@v1.3.4
      with:
        ref: ${{ github.ref }}
        check-name: 'Build full npm cache'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
    - name: Restore Builds
      id: cache-builds-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.npm
        key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
    - run: cd documentation-website && npm install
    - run: cd documentation-website && npm run lighthouse
