name: documentation-website FTA
on:
  push:
    branches:
    - master
    paths:
    - 'documentation-website/**.ts'
    - 'documentation-website/**.tsx'
    - 'documentation-website/**.js'
    - 'documentation-website/**.cjs'
    - 'documentation-website/**.json'
    - 'documentation-website/**.svelte'
    - '.github/workflows/documentation-website.fta.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'documentation-website/**.ts'
    - 'documentation-website/**.tsx'
    - 'documentation-website/**.js'
    - 'documentation-website/**.cjs'
    - 'documentation-website/**.json'
    - 'documentation-website/**.svelte'
    - '.github/workflows/documentation-website.fta.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            documentation-website/package-lock.json
            history-microservice/package-lock.json
            history-website/package-lock.json
            cli/package-lock.json
            package-lock.json
      - run: npm ci
      - run: cd documentation-website && npm ci && npm run language
      - run: npm run fta -- documentation-website || true
