name: documentation-website license lint
on:
  workflow_run:
    types:
      - completed
    workflows:
      - NPM Cache
    paths:
      - 'documentation-website/package-lock.json'
      - '.github/workflows/documentation-website.license-check.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd documentation-website && npm ci
      - run: cd documentation-website && npx license-checker -- --production --onlyAllow="MIT;ISC;Apache-2.0;BSD-2-Clause;BSD-3-Clause;Python-2.0;LGPL-2.1;GPL-2.0;BlueOak-1.0.0;CC0-1.0;0BSD;WTFPL;Unlicense"
