name: documentation-website lighthouse check
on:
  push:
    branches:
    - the-one
    paths:
      - 'documentation-website/**.ts'
      - 'documentation-website/**.tsx'
      - 'documentation-website/**.js'
      - 'documentation-website/**.cjs'
      - 'documentation-website/package-lock.json'
      - '.github/workflows/documentation-website.lighthouse-check.yml'
  pull_request:
    branches:
    - the-one
    paths:
      - 'documentation-website/**.ts'
      - 'documentation-website/**.tsx'
      - 'documentation-website/**.js'
      - 'documentation-website/**.cjs'
      - 'documentation-website/package-lock.json'
      - '.github/workflows/documentation-website.lighthouse-check.yml'
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript-typescript
        queries: security-and-quality
        source-root: documentation-website
    - name: Install Nginx
      run: sudo apt-get update && sudo apt-get install -y nginx
    - name: Configure Nginx
      run: |
        # Replace the default Nginx configuration with your own
        sudo cp ./nginx.conf /etc/nginx/sites-available/default
        sudo systemctl restart nginx
    - name: Run Lighthouse Check
      run: |
        cd documentation-website && npm install
        cd documentation-website && npm run lighthouse
