name: TEST
on:
  workflow_run:
    types:
      - completed
    workflows:
      - NPM Cache
    paths:
    - '**.ts'
    - '**.tsx'
    - '**.js'
    - '**.cjs'
    - '**.json'
    - '.github/workflows/test.yml'
env:
  PREVIOUS_NODE_VERSION: ${{ vars.PREVIOUS_NODE_VERSION || 'lts/*' }}
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  mindmap-integration-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.PREVIOUS_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd mindmap && npm ci
      - run: cd mindmap && npm run test
      - run: mv ./mindmap/coverage ./
      - run: sed -i 's/SF:tools/SF:mindmap\/tools/' ./coverage/lcov.info
      - run: sed -i 's/SF:src/SF:mindmap\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: mindmap integration ${{ env.PREVIOUS_NODE_VERSION }}
  mindmap-integration-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd mindmap && npm ci
      - run: cd mindmap && npm run test
      - run: mv ./mindmap/coverage ./
      - run: sed -i 's/SF:tools/SF:mindmap\/tools/' ./coverage/lcov.info
      - run: sed -i 's/SF:src/SF:mindmap\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: mindmap integration ${{ env.CURRENT_NODE_VERSION }}
  framework-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.PREVIOUS_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd framework && npm ci
      - run: cd framework && npm run language
      - run: cd framework && npm run test
      - run: mv ./framework/coverage ./
      - run: sed -i 's/SF:src/SF:framework\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run ${{ env.PREVIOUS_NODE_VERSION }}
  framework-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd framework && npm ci
      - run: cd framework && npm run language
      - run: cd framework && npm run test
      - run: mv ./framework/coverage ./
      - run: sed -i 's/SF:src/SF:framework\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run ${{ env.CURRENT_NODE_VERSION }}
  cli-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.PREVIOUS_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd cli && npm ci
      - run: cd cli && npm run language
      - run: cd cli && npm run test
      - run: mv ./cli/coverage ./
      - run: sed -i 's/SF:src/SF:cli\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: cli ${{ env.PREVIOUS_NODE_VERSION }}
  cli-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd cli && npm ci
      - run: cd cli && npm run language
      - run: cd cli && npm run test
      - run: mv ./cli/coverage ./
      - run: sed -i 's/SF:src/SF:cli\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: cli ${{ env.CURRENT_NODE_VERSION }}
  framework-integration-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.PREVIOUS_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.PREVIOUS_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd framework && npm ci
      - run: cd framework && npm run language
      - run: cd framework && npm run integration
      - run: mv ./framework/coverage ./
      - run: sed -i 's/SF:src/SF:framework\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: integration ${{ env.PREVIOUS_NODE_VERSION }}
  framework-integration-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd framework && npm ci
      - run: cd framework && npm run language
      - run: cd framework && npm run integration
      - run: mv ./framework/coverage ./
      - run: sed -i 's/SF:src/SF:framework\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: integration ${{ env.CURRENT_NODE_VERSION }}
  framework-property:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd framework && npm ci
      - run: cd framework && npm run language
      - run: cd framework && npm run property
      - run: mv ./framework/coverage ./
      - run: sed -i 's/SF:src/SF:framework\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: property ${{ env.CURRENT_NODE_VERSION }}
  documentation-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd documentation-website && npm ci
      - run: cd documentation-website && npm run language
      - run: cd documentation-website && npm run assets
      - run: cd documentation-website && npm run test
      - run: mv ./documentation-website/coverage ./
      - run: sed -i 's/SF:src/SF:documentation-website\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run documentation-website
  documentation-e2e-1:
    runs-on: ubuntu-latest
    env:
      SPLIT: 5
      SPLIT_INDEX: 0
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd documentation-website && npm ci
      - run: cd documentation-website && npm run language
      - run: cd documentation-website && npm run e2e
      - run: mv ./documentation-website/coverage ./
      - run: sed -i 's/SF:src/SF:documentation-website\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run documentation-e2e-1
  documentation-e2e-2:
    runs-on: ubuntu-latest
    env:
      SPLIT: 5
      SPLIT_INDEX: 1
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd documentation-website && npm ci
      - run: cd documentation-website && npm run language
      - run: cd documentation-website && npm run e2e
      - run: mv ./documentation-website/coverage ./
      - run: sed -i 's/SF:src/SF:documentation-website\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run documentation-e2e-2
  documentation-e2e-3:
    runs-on: ubuntu-latest
    env:
      SPLIT: 5
      SPLIT_INDEX: 2
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd documentation-website && npm ci
      - run: cd documentation-website && npm run language
      - run: cd documentation-website && npm run e2e
      - run: mv ./documentation-website/coverage ./
      - run: sed -i 's/SF:src/SF:documentation-website\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run documentation-e2e-3
  documentation-e2e-4:
    runs-on: ubuntu-latest
    env:
      SPLIT: 5
      SPLIT_INDEX: 3
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd documentation-website && npm ci
      - run: cd documentation-website && npm run language
      - run: cd documentation-website && npm run e2e
      - run: mv ./documentation-website/coverage ./
      - run: sed -i 's/SF:src/SF:documentation-website\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run documentation-e2e-4
  documentation-e2e-5:
    runs-on: ubuntu-latest
    env:
      SPLIT: 5
      SPLIT_INDEX: 4
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd documentation-website && npm ci
      - run: cd documentation-website && npm run language
      - run: cd documentation-website && npm run e2e
      - run: mv ./documentation-website/coverage ./
      - run: sed -i 's/SF:src/SF:documentation-website\/src/' ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run documentation-e2e-5
  end:
    runs-on: ubuntu-latest
    needs:
      - framework-previous
      - framework-current
      - cli-previous
      - cli-current
      - framework-integration-current
      - framework-integration-previous
      - documentation-website
      - documentation-e2e-1
      - documentation-e2e-2
      - documentation-e2e-3
      - documentation-e2e-4
      - documentation-e2e-5
      - mindmap-integration-current
      - mindmap-integration-previous
      - framework-property
    steps:
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
