name: pull request size
on:
  pull_request:
    branches:
      - the-one
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            documentation-website/package-lock.json
            history-microservice/package-lock.json
            history-website/package-lock.json
            cli/package-lock.json
            package-lock.json
      - run: npm install -g "https://github.com/Idrinth/check-pr-length.git#patch-1"
      - run: git remote add base https://github.com/idrinth/api-bench.git
      - run: git config --global user.email "prs@example.com"
      - run: git config --global user.name "PRS"
      - run: git fetch base the-one
      - run: git switch the-one
      - run: git remote add pullrequest "https://github.com/${{github.event.pull_request.head.repo.full_name}}"
      - run: git fetch pullrequest "${GITHUB_HEAD_REF}"
      - run: git switch $GITHUB_HEAD_REF
      - run: check-pr-length --max=350 --total=500 --base=the-one --silent=false --exclude="package-lock.json;*/package-lock.json"
