name: history-website language lint
on:
  workflow_run:
    types:
      - completed
    workflows:
      - NPM Cache
    paths:
    - 'history-website/language/*.yml'
    - '.github/workflows/history-website.language-lint.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: npm ci
      - run: npm run check-language -- history-website
