name: mindmap validate
on:
  push:
    branches:
    - master
    paths:
      - 'mindmap/data.yml'
      - 'mindmap/assets/*'
      - '.github/workflows/mindmap.validate.yml'
  pull_request:
    branches:
    - master
    paths:
      - 'mindmap/data.yml'
      - 'mindmap/assets/*'
      - '.github/workflows/mindmap.validate.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            framework/package-lock.json
            documentation-website/package-lock.json
            history-microservice/package-lock.json
            history-website/package-lock.json
            mindmap/package-lock.json
            package-lock.json
      - run: cd mindmap && npm ci
      - run: cd mindmap && npm run validate
