name: mindmap license lint
on:
  push:
    branches:
      - master
    paths:
      - 'mindmap/package-lock.json'
      - '.github/workflows/mindmap.license-check.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'mindmap/package-lock.json'
      - '.github/workflows/mindmap.license-check.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: cd mindmap && npm ci
      - run: cd mindmap && npx license-checker -- --production --onlyAllow="MIT;ISC;Apache-2.0;BSD-2-Clause;BSD-3-Clause;Python-2.0;LGPL-2.1;GPL-2.0;BlueOak-1.0.0;CC0-1.0;0BSD;WTFPL;Unlicense"
