name: tools Knip
on:
  push:
    branches:
    - master
    paths:
    - 'tools/**.ts'
    - 'tools/**.tsx'
    - 'tools/**.js'
    - 'tools/**.cjs'
    - 'tools/**.json'
    - 'tools/**.svelte'
    - '.github/workflows/root.knip.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'tools/**.ts'
    - 'tools/**.tsx'
    - 'tools/**.js'
    - 'tools/**.cjs'
    - 'tools/**.json'
    - 'tools/**.svelte'
    - '.github/workflows/root.knip.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - run: npm run knip
